language: python
python:
- '2.7'
services: sqlite3
env:
- DJANGO=1.11.6
before_install:
- export DJANGO_SETTINGS_MODULE=transportadora_orgaos.settings
install:
- pip install -r requirements.txt
before_script:
- python manage.py check
script:
- ./manage.py test
deploy:
  provider: heroku
  api_key:
    secure: CyHGHc8hZymn7pryRDipgGhsg/IBNnk2wkQMTvYMY2t0fc1cmUDVp69W8hEzQ/ZstcZyn/5RMWvCN3+4GIdrdhjWNk7ZZFCKyZAO+rnsm3x/wY+4vGmAzW1RXUuxcaHiAjzEddTO2uSFVuvSydc8PSrksK//7KO9sI5CetFABCRIFNg/wpeyQUBsiokAfZNMUv2f5qxmnflGuoflFK7qgIU2XBwOg+tVlIxVfVCpzucAqw+GCqA5uH0NkN75CRFR/VdXhG43hVolkMXB4O5zJr+YiIYsN3R0ueGUovuF/AnbX0Xn6H5Q/OYplwIif8xlk+HFjVIFBIHIfvwCSFyTXqtBPh4wJ81Wzle31aXR93BmIn1TpOHYh1jXW52Jv8T8uflDrFdmOMqEQB6ntcjIdJp91tGfBdDkGi8BoZ6FJsjs8gLYgGfW7o2OTItHCHNa/fgR2Olcy64vCdfL9SFcjHZkbo1hHItd3cNnQjIf6p9nhM6q2+LrOS62T9nlv3Vv77OtYCjaGKWIoFgRLZRrD+BfVTxf5MLwRPmQb+G9Fb26ZCBB3/udGuHspJV1wByq1P3hChoSOzhO0mIldqw7vul3+HC0VNTvwLFbxLh2muX8ohb+0/Zespgdda5PL2H8wJIuVeiuae/abXsq0HVvXbj+kdTkgallxdSQq8ftk6g=
  app:
    master: transorg
    development: transorg-dev
notifications:
  email: false
  slack:
    secure: aJxYkW9/05IJ0jnz5viuJFDEGPR51vz7aY7lzAlsef3ip7I1ivUZyqG6iKgAdBHdTRelR3DR8eYANcNAEta3Tp/XpiV9RGKqXgvmk05wAIQjW8N1HsXdPBB/AZ66UEl56hb+mcJwRtJ6RwVZXEpZHlUT+aSPr3n+v5bEoy2KXBE4UNN8uWqcDwEdoPG7Z11I1iPB10Gow/iTASo2mwIbMemPZ1leEmAcjp0IuseCstTVbo0v46qIBLAESv6ZA3vEJSf+ZXtMCv94/uxDXuh7FU3dV8MskIBsEZNSDR9+J5mcBrGp4cYPi4p/IfipmGAtkth9X6yKBa/cAVpGcN6XqZtU3MVfQpya2PGqfZK6shVdsvmNXCETZLYrpIfgdCmjDRa0cRgdnjzlHv6TAdX7X7S0ypQvkeS9dlya2obca7R3FSFkDXS3hyFdoTDrmBp7LWYjfRme3Dp//6p9U4K8f4L3dWjRo1XIpnba3xzS46HbiGp7l+ZoZ4sr63vNLWh49aBAxG9mhrjDnSvChu10Otyig/H8THUC+im3zLUEKoz3RA89nxzA1rJS4QXyiVOq8Nd+BWTijVGWfBxurtxaQXQ+FhBECoiI3bltagMVDou3P41s/iISMzePRm0KsPHW1y/KKL6o+yAKhqCcGNUMUlPyrWvkOiAq4ykz/TXfrj0=
