language: python
python: 
    - "2.7"
services: sqlite3
env:
    - DJANGO=1.11.6
before_install:
    - export DJANGO_SETTINGS_MODULE=transportadora_orgaos.settings
install:
    - pip install -r requirements.txt
script:
    - pytest

